### ISSUE TITLE
Blank page appeared in the simulation

### ISSUE THREAD

**Issue by sravanthimodepu** [openedx-vlead/open-edx-virtual-queuing-networks-modelling-iitd#1]
While testing the lab, found an issue that the simulation is redirecting to the blank page
Below is the screenshot of the issue:
![queuing](https://user-images.githubusercontent.com/11156924/35208958-dcff35e4-ff70-11e7-98e5-42eb6e188749.png)

**Comment by sanchita-dixit** [comment]
The actual lab URL is also redirecting to this blank page itself. I have changed it to Under construction

**Comment by sravanthimodepu** [comment]
As the original lab also redirecting to the blank page, closing this issue.
